### PR TITLE
Added support for MFA.

### PR DESCRIPTION
**Pull request by StevenRasmussen**
First off, let me say that this was my first time doing anything in F# (I'm a C# dev) and so I apologize if there are better ways of doing things. Hopefully I didn't hit too far off the mark.

Re: Paket.Restore.targets - there were a bunch of changes made to this file when I ran the 'build' command before trying to compile the project in VS per the build instructions. Not sure if this is all necessary or not but I left it in there.

Since the actual proxy is different when creating it for MFA (uses CrmServiceClient instead of OrganizationServiceProxy) I had to update the code to accept an IOrganizationService in many places.

I appreciate your feedback and consideration of this PR.

### CODE REVIEW

**Comment by magesoe** [comment]
Added in version 4.4.0

**Comment by daryllabar** [comment]
Is there any documentation for how this is used? Or maybe an example Command line

**Comment by magesoe** [comment]
https://github.com/delegateas/Daxif/wiki/Using-different-auth-methods

**Comment by daryllabar** [comment]
@magesoe  how do those parameters work with the XrmDefinitelyTyped.exe?  

This:
```
XrmDefinitelyTyped.exe /method:ConnectionType.ClientSecret /mfaAppId:<GUID> /mfaClientSecret:<SECRET> 
```
just gives me this
```
Unable to generate TypeScript files: clientCredentials.UserName.UserName or clientCredentials.Windows.ClientCredential.UserName MUST be populated!
```

**Comment by magesoe** [comment]
Yeah I guess I should have elaborated more :D
`XrmDefinitelyTyped.exe /method:ClientSecret /mfaAppId:<GUID> /mfaClientSecret:<SECRET>`
That should work

**Pull request merged**
