### PR TITLE
Fixes #83 & #84 - synchronous execution of queries & missing typings in xrm.ts

### LINKED ISSUE #83: Synchronous version of the Query.Execute method
Sometimes synchronous execution of query is necessary, eg. CustomRule on EnableRule or PopulateQueryCommand on Ribbon. I think that this can't be handled in asynchronous way.

### PR DESCRIPTION
**Pull request by majakubowski**
Fixes #83 & #84 - synchronous execution of queries & missing typings in xrm.ts

### CODE REVIEW

**Comment by magesoe** [comment]
I don't like the way you have implemented synchronous execution. 
What happens if the async call you make inside your synchronous function takes a long time, or fails? I think we need to implement it differently, if we actually want synchronous execution.

**Comment by magesoe** [comment]
Here are some more thoughts on this PR.

After reading various discussions on the web, I believe that synchronous http requests should not be allowed, because of the effect it has on the end-user experience. Libraries such as jQuery has deprecated these calls for the same reason.

However, if a strong case can be put forward that it is needed in CRM, I will consider merging this PR. I still have a problem with the way the error case is handled right now. It would be nice if it was handled similarly to this
```typescript
executeSync() : T | Error {
  let ret: T | Error = new Error("Unexpected execution");
  this.executeRaw((x) => { ret = x }, (err) => { ret = err }, true, true);
  return ret;
}; 
```
This will force the user to consider the fact that an error can occur.

**Comment by magesoe** [comment]
Added fix to #84 in version 4.0.7

**Comment by majakubowski** [comment]
Hi, I followed the example of your source code and corrected my PR.. I think it is a good change. As I wrote above - I used synchronous functions only in a specific scenario - always with connection to ribbon functions.

**Comment by magesoe** [comment]
Okay, I'll consider the case of ribbons. 
Have you tested this implementation? The synchronous call will still use `onreadystatechange` to return the result, which I do not believe is valid on a synchronous XMLHttpRequest.

**Comment by majakubowski** [comment]
Without setting error - I already use it from December ;) With setting error - it also works fine.

**Comment by magesoe** [comment]
Added in version 4.3.0

**Pull request merged**
