### PR TITLE
Include lookup properties (OData annotations)

### PR DESCRIPTION
**Pull request by pederwagner**
Added an option to include data about lookup properties (logicalname and navproperty) as well as formatted values for lookup fields in retrieved records

### CODE REVIEW

**Comment by obkirneh** [comment]
@magesoe & @pederwagner :
What version is this update released in? I currently got v4.0.3 and dont have the XrmQuery option ".includeFormattedValuesAndLookupProperties()".
I only have ".includeFormattedValues()"

PS: Just started with TypeScript and XrmDefinitelyTyped a month ago and are still learning..  And I love it so far... :)

**Comment by magesoe** [comment]
Looks like I did everything but press publish after I merged the PR. Sorry about that.
If I ever meet someone who waited for this feature, I'll buy you a beer...

**Comment by obkirneh** [comment]
Hi @magesoe,
I will update to v4.0.4 and give it a try.
Thanks,
Henrik

**Comment by obkirneh** [comment]
Hi @magesoe,

When I add .includeFormattedValuesAdnLookupProperties() I loose intelisense on the result.
Noticed this difference in dg.xrmquery.web.d.ts:

>/**
>         * Sets a header that lets you retrieve formatted values as well. Should be used after using select and expand of attributes.
>         */
        includeFormattedValues(): Query<FormattedResult & Result>;
>        /**
>         * Sets a header that lets you retrieve formatted values and lookup properties as well. Should be used after using select and expand of attributes.
>         */
        includeFormattedValuesAndLookupProperties(): Query<(FormattedResult & Result)[]>;

Is this correct:
> Query<(FormattedResult & Result)[]>;

.. or should `[]` be removed?

I also miss the `_lookuplogicalname?: string;` in the generated .d.ts file in interface `_formattedResult`

Hope above makes sense.. 

/Henrik

**Comment by magesoe** [comment]
This pull request did not include the typings for the new values, so they exist in the javascript object, but can not be accessed strongly typed. 
Perhaps we can ask @pederwagner, or someone else, for another pull request that adds the typings. You can seek inspiration from the way FormattedValues is implemented.

**Pull request merged**
