### PR TITLE
Added addOnPreProcessStatusChange and addOnPreStageChange to ProcessModule

### PR DESCRIPTION
**Pull request by OliverFlint**
Added support for:
`formContext.data.process.addOnPreProcessStatusChange(myFunction);`
and;
`formContext.data.process.addOnPreStageChange(myFunction);`
*including the corresponding `remove` functions*

### CODE REVIEW

**Comment by magesoe** [comment]
Fixes #177

**Comment by sergeytunnik** [comment]
Looks like this PR doubled addOnPreProcessStatusChange and removeOnPreProcessStatusChange method definitions for ProcessModule. Lines 1296 and 803, 1303 and 809.
Cause it's all in one file maybe better to merge both ProcessModule interface definitions into single..

**Comment by TomMalow** [comment]
Nice catch @sergeytunnik. Will try to merge the two interfaces together.

**Comment by TomMalow** [comment]
Released new version 5.3.1 that merge the two modules

**Pull request merged**
