### PR TITLE
roles and securityRoles typings.

### PR DESCRIPTION
**Pull request by sergeytunnik**
Related to #166, #171.

### CODE REVIEW

**Comment by TomMalow** [comment]
Really good PR. However, there are some changes we would like.

The deprecation of `securityRoles` should be moved to our xrm.d.ts extension files so that we can remove it but still include it in the generated files if the flag "use depreciated is used. 
The file should have the format "xrm_ext_9-9.1-.d.ts" to say that it was included in version 9 but deprecated in 9.1.

Additionally. A new interface for  a read only collection is added. However, we have something similar `Xrm.Collection`. Can we reuse the existing collection interface instead? Do they overlap 100% or are there differences? If so, can we extend "Xrm.Collection" so that it matches?

**Comment by sergeytunnik** [comment]
Looks like Collection's get method serves as entry to point to other get* methods. Changed roles to Collection<>.
Moved securityRoles to new extensions file.

**Comment by TomMalow** [comment]
Hi @sergeytunnik I took the liberty to move you changes to a new extension file targeting version 9.1 and up. I think that should be all and we will merge this PR in

**Comment by TomMalow** [comment]
Thank you for the changes @sergeytunnik. Appreciate the help with maintaining the tool

**Comment by magesoe** [comment]
Added in 5.2.0

**Pull request merged**
